dist: trusty
sudo: false

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

matrix:
  include:
    - env: DISTRIB="ubuntu" PYTHON_VERSION="2.7" DEPS=true
      addons:
        apt:
          packages:
              - python-numpy
    - env: DISTRIB="conda" PYTHON_VERSION="2.7" DEPS=true
    - env: DISTRIB="conda" PYTHON_VERSION="3.4" DEPS=true
    - env: DISTRIB="conda" PYTHON_VERSION="3.5" DEPS=true
    - env: DISTRIB="conda" PYTHON_VERSION="3.6" DEPS=true
    - env: DISTRIB="pypy" PYTHON_VERSION="2.7" DEPS=true
    - env: DISTRIB="pypy" PYTHON_VERSION="3.5" DEPS=true
    - env: DISTRIB="ubuntu" PYTHON_VERSION="2.7" DEPS=false
    - env: DISTRIB="conda" PYTHON_VERSION="2.7" DEPS=false
    - env: DISTRIB="conda" PYTHON_VERSION="3.4" DEPS=false
    - env: DISTRIB="conda" PYTHON_VERSION="3.5" DEPS=false
    - env: DISTRIB="conda" PYTHON_VERSION="3.6" DEPS=false
    - env: DISTRIB="pypy" PYTHON_VERSION="2.7" DEPS=false
    - env: DISTRIB="pypy" PYTHON_VERSION="3.5" DEPS=false

install: source build_tools/travis/install.sh

script:
  - py.test --cov=pydicom tests

after_success:
  - codecov
